### ISSUE TITLE
Duplicate labels

### ISSUE THREAD

**Issue by regan-karlewicz** [TinkurLab/monorepo-pr-labeler-action#44]
Hi! My client has been using this action in their monorepo without any configuration change in the last 4 months. We've recently been hitting an issue where our pull requests are getting multiple tags for the same sub-repo. 

This is our current configuration:

```
name: pr-labeler

on: pull_request

jobs:
  labelPR:
    name: Label PR With Repo(s)
    runs-on: ubuntu-latest
    steps:
      - name: Label PRs
        uses: tinkurlab/monorepo-pr-labeler-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_DIRS: 'services|packages'
        with:
          prefix: '🗂 '
```

When inspecting the created labels, I found this in the Github address bar:

```
https://github.com/<ORG>/<REPO>/labels/%F0%9F%97%82%20%20frontend
https://github.com/<ORG>/<REPO>/labels/%F0%9F%97%82%20frontend
```

Notice that one of the labels has an extra space between the prefix and label. 

I've been looking over the source code here and am not sure how this is possible, does anyone have any ideas? Maybe there is a missing string trim somewhere.
