### ISSUE TITLE
Combined usage with actions/labeler

### ISSUE THREAD

**Issue by jenssimon** [TinkurLab/monorepo-pr-labeler-action#57]
Are there recommendations how to use this action combined with [`actions/labeler`](https://github.com/actions/labeler)?

## Question

>❓**What happens when both workflows run at the same time?**

Sometimes this configuration leads to moments like

> [github-actions](https://github.com/apps/github-actions) bot added [🗂 foo](https://foo.bar) [🗂 bar](https://foo.bar) [dependencies](https://foo.bar) and removed [🗂 foo](https://foo.bar) [🗂 bar](https://foo.bar) labels [4 minutes ago](https://foo.bar)

I think

- `pull_request` and `pull_request_target` - no difference between workflow execution for both events
- it could happen that both workflows run at the same time

I haven't checked yet if it makes sense to run both actions within the same workflow.

> :bulb: I wonder if there is a recommendation how to use both actions within the same repo.

## Example code

Currently I run this configuration for a project using a monorepo:

```yaml
# .github/workflows/labeler.yml
name: Pull Request Labeler
on:
  - pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
```

```yaml
# .github/workflows/monorepo-pr-labeler-action.yml
name: Monorepo PR Repo Labeler
on:
  pull_request:
    paths:
    - services/**
    - packages/**

jobs:
  labelPR:
    name: Label PR With Repo(s)
    runs-on: ubuntu-latest
    steps:
      - name: Monorepo PR Repo Labeler
        uses: TinkurLab/monorepo-pr-labeler-action@4.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_DIRS: 'services|packages'
        with:
          prefix: '🗂'
          separator: ' '
```

```yaml
# .github/labeler.yml
dependencies:
  - '**/package.json'
  - ...

infra:
  - infrastructure/**/*
  - ...

ci:
  - .github/**
  - ...
```

So I can label changes for a PR on

- 🔀 dependencies
- ⚙️ ci
- 🗂 packages of the monorepo
